config={1:{1:'./latex/source/soal/1.tex',2:'./latex/source/soal/2.tex',3:'./latex/source/soal/3.tex',4:'./latex/source/soal/4.tex',5:'./latex/source/soal/5.tex',6:'./latex/source/soal/6.tex',7:'./latex/source/soal/7.tex',8:'./latex/source/soal/8.tex',9:'./latex/source/soal/9.tex',10:'./latex/source/soal/10.tex',11:'./latex/source/soal/11.tex','head':'./latex/source/soal/uashead.tex','tail':'./latex/source/soal/uastail.tex','after':'./latex/source/soal/after.tex'},

2:{1:'./latex/source/solusi/1sol.tex',2:'./latex/source/solusi/2sol.tex',3:'./latex/source/solusi/3sol.tex',4:'./latex/source/solusi/4sol.tex',5:'./latex/source/solusi/5sol.tex',6:'./latex/source/solusi/6sol.tex',7:'./latex/source/solusi/7sol.tex',8:'./latex/source/solusi/8sol.tex',9:'./latex/source/solusi/9sol.tex',10:'./latex/source/solusi/10sol.tex','head':'./latex/source/solusi/kuncihead.tex','tail':'./latex/source/solusi/kuncitail.tex','after':'./latex/source/solusi/after.tex'},

3:{1:'./latex/source/col2/1.tex',2:'./latex/source/col2/2.tex',3:'./latex/source/col2/3.tex',4:'./latex/source/col2/4.tex',5:'./latex/source/col2/5.tex',6:'./latex/source/col2/6.tex',7:'./latex/source/col2/7.tex',8:'./latex/source/col2/8.tex',9:'./latex/source/col2/9.tex',10:'./latex/source/col2/10.tex','head':'./latex/source/col2/uashead.tex','tail':'./latex/source/col2/uastail.tex','after':'./latex/source/solusi/after.tex'},

4:{1:'./latex/source/newspaper/1.tex',2:'./latex/source/newspaper/2.tex',3:'./latex/source/newspaper/3.tex',4:'./latex/source/newspaper/4.tex',5:'./latex/source/newspaper/5.tex',6:'./latex/source/newspaper/6.tex',7:'./latex/source/newspaper/7.tex',8:'./latex/source/newspaper/8.tex',9:'./latex/source/newspaper/9.tex',10:'./latex/source/newspaper/10.tex',11:'./latex/source/newspaper/11.tex',12:'./latex/source/newspaper/12.tex',13:'./latex/source/newspaper/13.tex',14:'./latex/source/newspaper/14.tex','head':'./latex/source/newspaper/uashead.tex','tail':'./latex/source/newspaper/uastail.tex','after':'./latex/source/newspaper/after.tex'},

5:{1:'./latex/source/itemsoal/1.tex',2:'./latex/source/itemsoal/2.tex',3:'./latex/source/itemsoal/3.tex',4:'./latex/source/itemsoal/4.tex',5:'./latex/source/itemsoal/5.tex',6:'./latex/source/itemsoal/6.tex',7:'./latex/source/itemsoal/7.tex',8:'./latex/source/itemsoal/8.tex',9:'./latex/source/itemsoal/9.tex',10:'./latex/source/itemsoal/10.tex',11:'./latex/source/itemsoal/11.tex',12:'./latex/source/itemsoal/12.tex',13:'./latex/source/itemsoal/13.tex',14:'./latex/source/itemsoal/14.tex','head':'./latex/source/itemsoal/head.tex','tail':'./latex/source/itemsoal/tail.tex','after':'./latex/source/itemsoal/after.tex'},

6:{1:'./latex/source/itemsoalessay/1.tex',2:'./latex/source/itemsoalessay/2.tex',3:'./latex/source/itemsoalessay/3.tex',4:'./latex/source/itemsoalessay/4.tex',5:'./latex/source/itemsoalessay/5.tex',6:'./latex/source/itemsoalessay/6.tex',7:'./latex/source/itemsoalessay/7.tex',8:'./latex/source/itemsoalessay/8.tex',9:'./latex/source/itemsoalessay/9.tex',10:'./latex/source/itemsoalessay/10.tex',11:'./latex/source/itemsoalessay/11.tex',12:'./latex/source/itemsoalessay/12.tex',13:'./latex/source/itemsoalessay/13.tex',14:'./latex/source/itemsoalessay/14.tex','head':'./latex/source/itemsoalessay/head.tex','tail':'./latex/source/itemsoalessay/tail.tex','after':'./latex/source/itemsoalessay/after.tex'}, 


7:{1:'./latex/source/itemsoalsolusi/1.tex',2:'./latex/source/itemsoalsolusi/2.tex',3:'./latex/source/itemsoalsolusi/3.tex',4:'./latex/source/itemsoalsolusi/4.tex',5:'./latex/source/itemsoalsolusi/5.tex',6:'./latex/source/itemsoalsolusi/6.tex',7:'./latex/source/itemsoalsolusi/7.tex',8:'./latex/source/itemsoalsolusi/8.tex',9:'./latex/source/itemsoalsolusi/9.tex',10:'./latex/source/itemsoalsolusi/10.tex',11:'./latex/source/itemsoalsolusi/11.tex',12:'./latex/source/itemsoalsolusi/12.tex',13:'./latex/source/itemsoalsolusi/13.tex',14:'./latex/source/itemsoalsolusi/14.tex','head':'./latex/source/itemsoalsolusi/head.tex','tail':'./latex/source/itemsoalsolusi/tail.tex','after':'./latex/source/itemsoalsolusi/after.tex'} 
}

